# Generated by Django 4.2.4 on 2023-08-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "price_per_night",
                    models.PositiveIntegerField(
                        help_text="Postive Number Only", verbose_name="Price"
                    ),
                ),
                ("description", models.TextField()),
                ("address", models.CharField(max_length=128)),
                (
                    "pet_allowed",
                    models.BooleanField(
                        default=False,
                        help_text="This house allows pets?",
                        verbose_name="Pets Allowed?",
                    ),
                ),
            ],
        ),
    ]
