# Generated by Django 4.2.4 on 2023-08-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_house_pet_allowed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='adress',
            new_name='address',
        ),
    ]
